import React from 'react';
import Head from 'next/head';
import { Box, CircularProgress, createStyles } from '@mui/material';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles(() => createStyles({
  flexDefault: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bgColorGreen: {
    backgroundColor: '#7cccab'
  },
  bgColorBlue: {
    backgroundColor: '#009a8a'
  }
}));

interface IProps {
  veiculo: string | any,
  loading: boolean
}

const ResultadoPage = ({ veiculo, loading }: IProps) => {

  const styles: any = useStyles()

  return (
    <>
      <Head>
        <title>Mobiauto - FIPE | Resultado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && (
        <Box 
          component='div'
          className={styles.flexDefault}
          minHeight='100vh'
        >
          <CircularProgress />
        </Box>
      )}
      {!loading && (
        <Box
          component='div'
          minHeight='100vh'
          className={styles.flexDefault}
        >
          <Box
            component='div'
            flexDirection='column'
            width='100vw'
            padding={2}
            gap={2}
            className={`${styles.flexDefault} ${styles.bgColorGreen}`}
          >
            <h2 style={{margin: 0}}>{`Tabela Fipe: Preço ${veiculo?.Marca} ${veiculo?.AnoModelo}`}</h2>
            <Box
              component='div'
              p={2}
              color='#fff'
              borderRadius='50px'
              textTransform='uppercase'
              fontSize='18px'
              fontWeight='700'
              className={styles.bgColorBlue}
            >
              {veiculo?.Valor}
            </Box>
            <Box
              component='small'
              color='#333'
            >
              Este é o preço de compra do veículo.
            </Box>
          </Box>
        </Box>
      )}
    </>
  )
}

export default ResultadoPage